### ISSUE TITLE
Protótipos do sistema

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#10]
Eu como **desenvolvedor** quero **criar os protótipo das páginas** para **o usuário conseguir acessar o sistema.**

- [x] Tela de login;
- [x] Tela home de usuário logado;
- [x] Perfil do usuário;
- [x] Ranking

**Comment by Gleicianegaldino** [comment]
- [ ] Tela de login;
- [ ] Tela home de usuário logado;
- [ ] Perfil do usuário;
- [ ] Ranking

Para a resolução desta issue foi criado um Team Project - Design de Interface (UI) no figma, com a participação de todos colaboradores do projeto.


https://www.figma.com/files/project/43059670/Team-project?fuid=1042897671264608362
