### ISSUE TITLE
Elaborar modelo conceitual

### ISSUE THREAD

**Issue by lilialnas** [desireefernandes/TutorEasy#2]
Eu como **desenvolvedor** quero **construir um modelo conceitual** para **identificar as minhas entidades, atributos e relacionamentos** do meu projeto.

- [x] Selecionar uma ferramenta on-line para modelo conceitual
- [x] Identificar as entidades
- [x] Identificar os atributos
- [x] Identificar os relacionamentos
- [x] Gerar arquivo de exportação (.PNG, .PDF)

**Comment by Gleicianegaldino** [comment]
O commite realizado foi a atualização do projeto para o estilo onepage, todas as páginas existentes foram realocadas e melhoradas, as imagens adicionadas são para exemplificar e serão alteradas futuramente. O commit realizado nessa issue foi **errado**, era para issue #5 por se tratar do Front-end.

Peço desculpas para os colaboradores dessa issue #2.

**Comment by desireefernandes** [comment]
![DEM](https://user-images.githubusercontent.com/56517478/142346438-5fd2057d-b30a-4127-95de-180f8e46e606.jpeg)
