### ISSUE TITLE
Alterações header & footer

### ISSUE THREAD

**Issue by Gleicianegaldino** [desireefernandes/TutorEasy#21]
Eu como **desenvolvedor** quero **alterar o header e footer** para **criar uma melhor experiencia para o usuário.**

- [ ] Colar footer na base das páginas
- [x] Alterar header
- [x] Alterar footer
- [x] Alterar nome para logotipo

**Comment by desireefernandes** [comment]
https://github.com/desireefernandes/TutorEasy/commit/63f387263da38f3e8d918d09c8f9c9131a9ad8ec
