### ISSUE TITLE
CRUD Tutorial

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#22]
Eu como **desenvolvedor** quero **desenvolver o CRUD de tutorial** para **o usuário criar tutoriais no sistema.**

- [x] #23  
- [x] #24  
- [x] #25 
- [x] #26

**Comment by Gleicianegaldino** [comment]
CRUD Tutorial - sem função upload de imagens, feito de forma simples para ser aprimorado futuramente. 

- [ ] Tutorial - CREATE #23
- [ ] Tutorial - READ #24
- [ ] Tutorial - UPDATE #25
- [ ] Tutorial - DELETE #26
