### ISSUE TITLE
Identidade visual do sistema

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#6]
Eu como **desenvolvedor** quero **criar o design e identidade visual da plataforma** para **criar um sistema elegante que ofereça uma boa experiência para o usuário.**

- [x] Análise e estudo para criação do logotipo
- [x] Análise e estudo para escolha da paleta
- [x] Definição da paleta
- [x] Criação dos modelos do logotipo
- [x] Criação do logotipo

**Comment by Aline-Martinneli** [comment]
![image](https://user-images.githubusercontent.com/87158232/142051889-84337f7d-0ed7-4908-a353-03a603e7a03b.png)

Optamos por começar com uma logo simples e clean, com as cores escolhidas, ainda faltam ajustes, mas já está encaminhada
