### ISSUE TITLE
Protótipo da tela inicial

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#7]
Eu como **desenvolvedor** quero **criar o protótipo da página inicial** para **o usuário conseguir acessar o sistema.**

- [x] Estudo de estilos de design e interface a serem implementados
- [x] Estudo da identidade visual do site
- [x] Criação do protótipo de baixa fidelidade
- [x] Criação do protótipo de alta fidelidade

**Comment by Gleicianegaldino** [comment]
- [ ] Criação do protótipo de alta fidelidade

![01](https://user-images.githubusercontent.com/78940661/142260058-6b257104-fb2b-4661-8a1f-15ec670fae3e.jpg)
