### ISSUE TITLE
Estudo framework CSS - Semantic UI

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#9]
Eu como **desenvolvedor** quero **estudar como utilizar o framework Semantic UI** para **criar um sistema elegante que ofereça uma boa experiência para o usuário.**

**Comment by Gleicianegaldino** [comment]
Para o desenvolvimento da página de login utilizamos o layout do semantic UI.
https://semantic-ui.com/examples/login.html
